#!/stage1/sh
export _PATH="$PATH"
export PATH="/stage1"

date >>/boot.txt
exec >>/boot.txt 2>&1
cd /
mount -t proc proc /proc
mount -t sysfs sysfs /sys

rm /init

bml_over_mtd dump boot 72 reservoir 2004 /stage1/boot.bin

load_image=/stage1/boot.cpio

mount -t ext4 /dev/block/mmcblk0p2 /system
mount -t ext4 /dev/block/mmcblk0p1 /cache

if test -e /cache/.startrecovery || grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	rm -fr /cache/.startrecovery

	load_image=/stage1/recovery.cpio

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
elif ! test -e /system/build.prop ; then
	# emergency boot
        umount /cache
        make_ext4fs -b 4096 -g 32768 -i 8192 -I 256 -a /cache /dev/block/mmcblk0p1
        mount -t ext4 /dev/block/mmcblk0p1 /cache
        mkdir /cache/recovery

	mount -t vfat /dev/block/mmcblk1p1 /sdcard

	UPDATE=$(cat /sdcard/cyanogenmod.cfg)

	if test -e $UPDATE ; then
		echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
  	fi

	load_image=/stage1/recovery.cpio

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

umount /cache
umount /system
umount /sdcard
rm -rf /sdcard

cpio -i < ${load_image}

if grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	cp lpm.rc init.rc
	rm init.p1c.rc
fi

umount /sys
umount /proc
date >> /boot.txt

rm -rf /stage1 
rm -rf /dev/*

export PATH="${_PATH}"

exec /init
