#!/stage1/sh
export _PATH="$PATH"
export PATH="/stage1"

date >>/boot.txt
exec >>/boot.txt 2>&1
cd /
mount -t proc proc /proc
mount -t sysfs sysfs /sys

rm /init

bml_over_mtd dump boot 72 reservoir 2004 /stage1/boot.bin

eval $(grep -m 1 -A 1 BOOT_IMAGE_OFFSETS /stage1/boot.bin | tail -n 1)

load_offset=$boot_offset
load_len=$boot_len

mount -t yaffs2 /dev/block/mtdblock2 /system
mount -t yaffs2 /dev/block/mtdblock3 /cache

if test -e /cache/.startrecovery || grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	rm -fr /cache/.startrecovery
	load_offset=$recovery_offset
	load_len=$recovery_len

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
elif ! test -e /system/build.prop ; then
	# emergency boot
        umount /cache
        erase_image cache
        mount -t yaffs2 /dev/block/mtdblock3 /cache
        mkdir /cache/recovery

	mount -t vfat /dev/block/mmcblk1p1 /sdcard

	UPDATE=$(cat /sdcard/cyanogenmod.cfg)

	if test -e $UPDATE ; then
		echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
  	fi

	load_offset=$recovery_offset
	load_len=$recovery_len

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
fi

umount /cache
umount /system
umount /sdcard
rm -rf /sdcard

dd bs=512 if=/stage1/boot.bin skip=$load_offset count=$load_len | zcat | cpio -i

if grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	cp lpm.rc init.rc
	rm init.p1c.rc
fi

umount /sys
umount /proc
date >> /boot.txt

rm -rf /stage1 
rm -rf /dev/*

export PATH="${_PATH}"

exec /init
