#!/stage1/sh
export _PATH="$PATH"
export PATH="/stage1"

date >>/boot.txt
exec >>/boot.txt 2>&1
cd /
mount -t proc proc /proc
mount -t sysfs sysfs /sys

rm /init

bml_over_mtd dump boot 72 reservoir 2004 /stage1/boot.bin

load_image=/stage1/boot.cpio

# find the sdcard
CACHE='/dev/block/mmcblk0p1'
SDCARD='/dev/block/mmcblk1p1'
if test `cat /sys/devices/platform/s3c-sdhci.0/mmc_host/mmc0/mmc0:0001/type` != "MMC" ; then
	# user has removed the eMMC
	CACHE='/dev/block/mmcblk0p3'
	SDCARD='/dev/block/mmcblk0p1'
fi
mount -t vfat "$SDCARD" /sdcard

# check for sdcard hacks
if test -e /sdcard/activate_data_on_sdcard.zip ; then
	mkdir /tmp
	unzip /sdcard/activate_data_on_sdcard.zip -d /tmp
fi

mount -t yaffs2 /dev/block/mtdblock2 /system
mount -t ext4 "$CACHE" /cache

if test -e /cache/.startrecovery || grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	rm -fr /cache/.startrecovery

	load_image=/stage1/recovery.cpio

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
elif ! test -e /system/build.prop ; then
	# emergency boot
        umount /cache
        make_ext4fs -b 4096 -g 32768 -i 8192 -I 256 -a /cache "$CACHE"
        mount -t ext4 "$CACHE" /cache
        mkdir /cache/recovery

	UPDATE=$(cat /sdcard/cyanogenmod.cfg)

	if test -e $UPDATE ; then
		echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
  	fi

	load_image=/stage1/recovery.cpio

	# disable lpm
	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
else
	# don't install recovery.fstab when booting android
	rm -rf /tmp/etc
fi

umount /cache
umount /system
umount /sdcard
rm -rf /sdcard

cpio -i < ${load_image}

if grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
	# low power mode
	cp lpm.rc init.rc
	rm init.p1c.rc
fi

if test -d /tmp ; then
	cp -a /tmp/* /
	rm -rf /tmp
fi

umount /sys
umount /proc
date >> /boot.txt

rm -rf /dev/*
rm -rf /stage1

export PATH="${_PATH}"

exec /init
